# Generated by Django 6.0.1 on 2026-01-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='max_players',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
