# Generated by Django 5.2.10 on 2026-02-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_alter_court_id'),
        ('matches', '0003_alter_match_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('court', 'start_time'), name='unique_match_per_court_and_start_time'),
        ),
    ]
