# Generated by Django 6.0.1 on 2026-01-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
